### ISSUE TITLE
Latest gitignore in vs and unity is conflict (about *.meta file)

### ISSUE THREAD

**Issue by lightjiao** [toptal/gitignore.io#510]
### Development Environment:

- [x] Machine (Local, Container, Virtual):
Local
- [x] Operating System (Name/Version):
Macos
- [x] Web Browser (Name/Version):
chrome
- [x] Vapor Version:
- [x] Swift Version:

### Expected Behavior:
Generate unity vs gitignore file, there are two patterns conflict:
in unity
```
# Asset meta data should only be ignored when the corresponding asset is also ignored
!/[Aa]ssets/**/*.meta
```
in vs:
```
# Files built by Visual Studio
*_i.c
*_p.c
*_h.h
*.ilk
*.meta
```

the last pattern `*.meta` override the previous pattern `!/[Aa]ssets/**/*.meta` , that means, every `*.meta` file is ignored which I don't want to see.

I creat and push a repo on my windows, and checkout on my mac today. And then everything in unity scene and shader don't work on my mac.
It tooks me 2 hour to read the [official gitignore document](https://git-scm.com/docs/gitignore) and your latest commit and test to know what happened.

**Yes, I can generate the unity template after the vs template to aviod my conflict**
> **After Regerate: 💔I cannot generate the unity template after the vs template**
But, I would suggest the `gitignore.io` web service can set the `!` prefix pattern always on the last of the `.gitignore` file to avoid this problem I met today (to save other many people's time).

My English is not very well, thanks reading. 
比心❤️

**Comment by christianlerke** [comment]
Hi @lightjiao,
This sounds like an issue with the template.
Please open a PR with the required changes here: https://github.com/toptal/gitignore/tree/master/templates

**Comment by amrezzd** [comment]
Hi @christianlerke,
It seems the issue still exists. The problem is with VS and Unity patterns order. If you try the followings:

- https://www.toptal.com/developers/gitignore/api/visualstudio,unity
- https://www.toptal.com/developers/gitignore/api/unity,visualstudio

In both cases VS patterns are added after Unity patterns. This way we'd have `*.meta` pattern after `!/[Aa]ssets/**/*.meta` which will override it.
